### ISSUE TITLE
scrape from multiple servers/domains?

### ISSUE THREAD

**Issue by Nurlan199206** [nginxinc/nginx-prometheus-exporter#72] opened 2019-11-14 09:00 UTC
how to scrape from multiple domains/servers?

i tried args like that

` - "--nginx.scrape-uri=https://domain1.kz/basic_status, https://domain2.kz/basic_status"`

but prometheus showing only one.

**Comment by Nurlan199206** [comment] 2019-11-14 09:03
ok, i ran two deployments.. seems it's works...


```
nginx_connections_active{instance="172.16.5.164:9113",job="kubernetes-service-endpoints",kubernetes_name="nginx-exporter-service2",kubernetes_namespace="default"} | 7
-- | --
nginx_connections_active{instance="172.16.5.181:9113",job="kubernetes-service-endpoints",kubernetes_name="nginx-exporter-service",kubernetes_namespace="default"} | 188
```

**Comment by Rulox** [comment] 2019-11-14 11:32
Hi @Nurlan199206 

Yes, it is not possible to add multiple servers on the `scrape-uri` argument, the way you solved the problem is the correct way, 1 exporter per NGINX instance.

Let me know if that's ok and we can close the issue,
Thanks!

**Closed** 2019-11-14 11:39 UTC
