### ISSUE TITLE
how to use in  'arm64' architecture?

### ISSUE THREAD

**Issue by cooltushar** [nginxinc/nginx-prometheus-exporter#122] opened 2020-09-21 10:58 UTC
i'm trying to use binary but unfortunately failed. can you please describe how to configure for arm64 base os.

**Comment by Dean-Coakley** [comment] 2020-09-30 14:46
@cooltushar Do you have an error message you can share?

If we were to offer am `arm64` docker image would that solve your problem, or do you need to run this as a binary?

**Comment by cooltushar** [comment] 2020-10-13 05:08
@Dean-Coakley error: standard_init_linux.go:190: exec user process caused "exec format error"

This would be a good thing if you provided a docker image.

**Comment by Dean-Coakley** [comment] 2020-10-19 13:57
Closing as a duplicate of: https://github.com/nginxinc/nginx-prometheus-exporter/issues/121

We will use that issue to track the progress of offering an `arm64` docker image.

**Closed by Dean-Coakley** 2020-10-19 13:57 UTC
